// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU4PvTUhRe3LbN3dUM6FuKlLHh7uVVDyo',
    appId: '1:24938906833:web:d7061960350b4b4434b1f0',
    messagingSenderId: '24938906833',
    projectId: 'flutter-workshop-4-epitech',
    authDomain: 'flutter-workshop-4-epitech.firebaseapp.com',
    storageBucket: 'flutter-workshop-4-epitech.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgun4lSc6CoLsZQi61JpB43D9x3wmIT3s',
    appId: '1:24938906833:android:c2495194d28daeb834b1f0',
    messagingSenderId: '24938906833',
    projectId: 'flutter-workshop-4-epitech',
    storageBucket: 'flutter-workshop-4-epitech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh5TEU99gUP6p71Sq2QlaLuhpX86AuR5w',
    appId: '1:24938906833:ios:460e473808f5234434b1f0',
    messagingSenderId: '24938906833',
    projectId: 'flutter-workshop-4-epitech',
    storageBucket: 'flutter-workshop-4-epitech.appspot.com',
    iosBundleId: 'com.example.workshops',
  );
}
