# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    firebase_app_distribution(
      app: "1:24938906833:android:c2495194d28daeb834b1f0",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end
